// GET /api/sessions/[id]/export?leafId=<id>&theme=<name>
//
// Returns the current leaf of the requested session as a single-file HTML
// document, generated by pi coding agent's built-in exporter (the same
// module backing the TUI's `/export` command). The result is fully
// self-contained: pi inlines marked + highlight.js + its session-tree
// sidebar JS, so the file opens identically on the receiver's machine.
//
// Errors:
//   404  session id not found
//   500  unexpected read/render failure

import { NextResponse } from "next/server";
import { SessionManager } from "@earendil-works/pi-coding-agent";

import { resolveSessionPath } from "@/lib/server/session-reader";
import { exportSessionHtmlViaPi } from "@/lib/server/session-export/pi-html";
import { createLogger, elapsedMs } from "@/lib/server/logger";

const log = createLogger("api/sessions/[id]/export");

// Same shape as `slugifyTitle` in app/api/todos/[id]/export/route.ts,
// widened so CJK + accented titles round-trip without losing meaning.
function slugifyTitle(title: string, fallbackId: string): string {
  const cleaned = title
    .replace(/[^\p{L}\p{N}一-鿿]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return cleaned.length > 0 ? cleaned : `session-${fallbackId.slice(0, 8)}`;
}

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const startedAt = Date.now();
  try {
    const { id } = await params;
    if (!id) {
      return NextResponse.json({ error: "id is required" }, { status: 400 });
    }

    const url = new URL(req.url);
    const leafId = url.searchParams.get("leafId");
    const themeName = url.searchParams.get("theme") ?? undefined;

    log.debug("export session requested", { id, leafId, themeName });

    // 1. Resolve on-disk path; 404 if missing.
    const filePath = await resolveSessionPath(id);
    if (!filePath) {
      log.warn("export session not found", { id, durationMs: elapsedMs(startedAt) });
      return NextResponse.json({ error: "session not found" }, { status: 404 });
    }

    // 2. Open the session via the SDK manager; this is what pi's exporter
    // also does internally in `exportFromFile`.
    const sm = SessionManager.open(filePath);

    // 3. Delegate HTML generation to pi's exporter. The helper handles
    // leaf switching and tmp-file round-tripping; we get a plain string
    // back to stream into a NextResponse.
    const html = await exportSessionHtmlViaPi(sm, {
      leafId,
      themeName,
    });

    // 4. Compose the attachment filename from the session name (if any).
    const sessionName =
      (typeof sm.getSessionName === "function" ? sm.getSessionName() : "") ?? "";
    const title =
      sessionName.length > 0 ? sessionName : `Session ${id.slice(0, 8)}`;
    const slug = slugifyTitle(title, id);

    log.info("session exported via pi", {
      id, slug, leafId, themeName,
      htmlBytes: html.length,
      durationMs: elapsedMs(startedAt),
    });

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(slug)}.html`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    log.error("export session failed", { error, durationMs: elapsedMs(startedAt) });
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 500 },
    );
  }
}