/**
 * Curated emoji choices for per-cwd custom icons, with a short English
 * keyword label used for search. Pickers render these in a grid; labels are
 * matched case-insensitively against the search query. The picker dedupes by
 * emoji character, so repeated glyphs here only show once.
 */
export interface CwdEmojiOption {
  emoji: string;
  label: string;
}

export const CWD_EMOJI_OPTIONS: CwdEmojiOption[] = [
  // ── Folders / files / storage ─────────────────────────────────────
  { emoji: "📁", label: "folder directory" },
  { emoji: "📂", label: "folder open directory" },
  { emoji: "🗂️", label: "card index file manager" },
  { emoji: "🗄️", label: "file cabinet archive database storage" },
  { emoji: "🗃️", label: "card box archive" },
  { emoji: "🗳️", label: "ballot box vote" },
  { emoji: "📄", label: "file page document" },
  { emoji: "📃", label: "page curling document" },
  { emoji: "📜", label: "scroll log" },
  { emoji: "📑", label: "bookmark tabs" },
  { emoji: "🗎", label: "blank document" },
  { emoji: "🗀", label: "new folder" },
  { emoji: "🗁", label: "open folder tray" },
  { emoji: "💾", label: "floppy disk save" },
  { emoji: "💽", label: "minidisc storage" },
  { emoji: "💿", label: "cd disc" },
  { emoji: "📀", label: "dvd disc" },
  { emoji: "🗒️", label: "spiral notepad" },
  { emoji: "🗓️", label: "spiral calendar date" },
  { emoji: "📋", label: "clipboard list" },
  { emoji: "📝", label: "memo note write" },
  { emoji: "📌", label: "pushpin pin" },
  { emoji: "📍", label: "round pushpin location" },
  { emoji: "📎", label: "paperclip" },
  { emoji: "🖇️", label: "paperclips link" },
  { emoji: "📏", label: "straight ruler" },
  { emoji: "📐", label: "triangle ruler" },
  { emoji: "✂️", label: "scissors" },
  { emoji: "🗑️", label: "wastebasket trash delete bin" },
  { emoji: "📦", label: "package box shipping" },
  { emoji: "🎁", label: "gift wrapped" },
  { emoji: "🗜️", label: "clamp compress" },
  { emoji: "🧰", label: "toolbox tools" },
  { emoji: "🧲", label: "magnet attract" },
  // ── Code / dev / terminal / git ───────────────────────────────────
  { emoji: "💻", label: "laptop code computer" },
  { emoji: "🖥️", label: "desktop monitor computer" },
  { emoji: "🖨️", label: "printer" },
  { emoji: "⌨️", label: "keyboard code cli" },
  { emoji: "🖱️", label: "computer mouse" },
  { emoji: "🖲️", label: "trackball" },
  { emoji: "🧑‍💻", label: "developer programmer" },
  { emoji: "👨‍💻", label: "man developer programmer" },
  { emoji: "👩‍💻", label: "woman developer programmer" },
  { emoji: "🤖", label: "robot bot" },
  { emoji: "🧠", label: "brain ai intelligence" },
  { emoji: "⚡", label: "high voltage lightning fast" },
  { emoji: "🔌", label: "electric plug api plugin" },
  { emoji: "🔋", label: "battery power" },
  { emoji: "🖧", label: "network three computers" },
  { emoji: "🖥️", label: "workstation server" },
  { emoji: "🐛", label: "bug debug" },
  { emoji: "🪲", label: "beetle debug" },
  { emoji: "🦠", label: "microbe virus" },
  { emoji: "🧾", label: "receipt invoice" },
  { emoji: "🗃️", label: "codebase archive" },
  // Git / repo / CI
  { emoji: "🦑", label: "squid git" },
  { emoji: "🐙", label: "octopus github octocat" },
  { emoji: "🌿", label: "herb branch" },
  { emoji: "🔀", label: "shuffle branch merge" },
  { emoji: "🔱", label: "trident branch release" },
  { emoji: "♻️", label: "recycle refactor rebase" },
  { emoji: "🌳", label: "tree commit history" },
  { emoji: "🚦", label: "traffic light ci status" },
  { emoji: "🚧", label: "construction barrier wip build" },
  { emoji: "✅", label: "check green done test pass" },
  { emoji: "❌", label: "cross red fail error" },
  { emoji: "🧪", label: "test tube lab test qa" },
  { emoji: "🎯", label: "target goal coverage" },
  { emoji: "🧮", label: "abacus math count" },
  { emoji: "🛠️", label: "hammer wrench tools fix" },
  { emoji: "🏗️", label: "construction building build" },
  { emoji: "🚀", label: "rocket launch deploy release" },
  { emoji: "📡", label: "satellite antenna signal deploy" },
  // ── Languages / frameworks / runtime ──────────────────────────────
  { emoji: "🐍", label: "snake python" },
  { emoji: "🦀", label: "crab rust" },
  { emoji: "☕", label: "hot beverage coffee java" },
  { emoji: "💎", label: "gem ruby reward" },
  { emoji: "🐹", label: "hamster go golang" },
  { emoji: "🐘", label: "elephant php mysql" },
  { emoji: "🐫", label: "camel twohumps perl" },
  { emoji: "🕊️", label: "dove swift peace" },
  { emoji: "🐿️", label: "squirrel chipmunk swift" },
  { emoji: "⚛️", label: "atom react physics" },
  { emoji: "🅰️", label: "a blood type angular alpha" },
  { emoji: "🅱️", label: "b blood type beta" },
  { emoji: "🐳", label: "whale docker container" },
  { emoji: "☸️", label: "wheel of dharma kubernetes" },
  { emoji: "🧊", label: "ice datawasm icicle" },
  { emoji: "🔷", label: "large blue diamond kotlin" },
  { emoji: "🟨", label: "yellow square typescript" },
  { emoji: "🟩", label: "green square go" },
  { emoji: "🟦", label: "blue square reactjs" },
  { emoji: "🟧", label: "orange square html rust" },
  { emoji: "🟪", label: "purple square" },
  { emoji: "🌶️", label: "hot pepper spicy" },
  // ── Data / database / infra / cloud ───────────────────────────────
  { emoji: "🗄️", label: "database server" },
  { emoji: "🛢️", label: "oil drum database" },
  { emoji: "🧃", label: "juice data" },
  { emoji: "🧮", label: "math calculator" },
  { emoji: "📊", label: "bar chart data stats" },
  { emoji: "📈", label: "chart increasing trend analytics" },
  { emoji: "📉", label: "chart decreasing trend down" },
  { emoji: "☁️", label: "cloud" },
  { emoji: "⛅", label: "sun behind cloud" },
  { emoji: "🌩️", label: "cloud lightning storm" },
  { emoji: "🌧️", label: "cloud rain" },
  { emoji: "❄️", label: "snowflake cold cache" },
  { emoji: "🌨️", label: "cloud snow" },
  { emoji: "🌫️", label: "fog" },
  { emoji: "🌪️", label: "tornado" },
  { emoji: "🛰️", label: "satellite space" },
  { emoji: "🖧", label: "network nodes" },
  { emoji: "🔗", label: "link chain" },
  { emoji: "🌐", label: "globe web internet i18n" },
  { emoji: "🌍", label: "globe europe web" },
  { emoji: "🌎", label: "globe americas" },
  { emoji: "🌏", label: "globe asia" },
  { emoji: "📶", label: "signal bars wifi" },
  { emoji: "📶", label: "cellular network" },
  { emoji: "🛜", label: "wireless" },
  { emoji: "🎛️", label: "control knobs" },
  { emoji: "⚙️", label: "gear settings config" },
  { emoji: "🔧", label: "wrench tool fix" },
  { emoji: "🔩", label: "nut and bolt" },
  { emoji: "🗜️", label: "clamp" },
  { emoji: "⏱️", label: "stopwatch perf" },
  { emoji: "⏲️", label: "timer clock" },
  { emoji: "🧭", label: "compass navigation discovery" },
  { emoji: "🧯", label: "fire extinguisher infra" },
  // ── Security / auth / compliance ──────────────────────────────────
  { emoji: "🔒", label: "lock secure" },
  { emoji: "🔓", label: "unlock" },
  { emoji: "🔐", label: "closed lock key auth" },
  { emoji: "🔑", label: "key access token" },
  { emoji: "🗝️", label: "old key" },
  { emoji: "🛡️", label: "shield security firewall" },
  { emoji: "🚨", label: "police car light alert alarm" },
  { emoji: "⚠️", label: "warning caution" },
  { emoji: "🚫", label: "prohibited deny block" },
  { emoji: "✅", label: "pass allow" },
  { emoji: "🕵️", label: "detective spy audit" },
  { emoji: "🛂", label: "passport control" },
  { emoji: "🧾", label: "audit receipt" },
  { emoji: "🔏", label: "locked with pen sign" },
  { emoji: "🔐", label: "security key" },
  { emoji: "🆔", label: "id identity" },
  // ── Business / finance / commerce ─────────────────────────────────
  { emoji: "💼", label: "briefcase business" },
  { emoji: "🎒", label: "backpack" },
  { emoji: "🏦", label: "bank finance" },
  { emoji: "💰", label: "money bag finance" },
  { emoji: "💵", label: "dollar banknote" },
  { emoji: "💶", label: "euro banknote" },
  { emoji: "💷", label: "pound banknote" },
  { emoji: "💴", label: "yen banknote" },
  { emoji: "💳", label: "credit card payment" },
  { emoji: "🧾", label: "receipt bill" },
  { emoji: "💱", label: "currency exchange" },
  { emoji: "🏷️", label: "label tag" },
  { emoji: "🛒", label: "shopping cart commerce" },
  { emoji: "🛍️", label: "shopping bags" },
  { emoji: "🏪", label: "convenience store" },
  { emoji: "📈", label: "stock growth" },
  { emoji: "⚖️", label: "balance scale legal" },
  { emoji: "🧾", label: "billing invoice" },
  { emoji: "🏧", label: "atm" },
  { emoji: "🪙", label: "coin crypto" },
  { emoji: "🧑‍💼", label: "office worker" },
  { emoji: "👩‍💼", label: "businesswoman" },
  { emoji: "👨‍💼", label: "businessman" },
  { emoji: "🤝", label: "handshake partner deal" },
  { emoji: "📉", label: "loss" },
  // ── Planning / project / status ───────────────────────────────────
  { emoji: "📅", label: "calendar schedule" },
  { emoji: "📆", label: "tear off calendar" },
  { emoji: "🗓️", label: "calendar plan" },
  { emoji: "⏰", label: "alarm clock deadline" },
  { emoji: "⏳", label: "hourglass time" },
  { emoji: "⌛", label: "hourglass done" },
  { emoji: "🕐", label: "one oclock time" },
  { emoji: "🕑", label: "clock time" },
  { emoji: "🔔", label: "bell notification" },
  { emoji: "🔕", label: "bell with slash mute" },
  { emoji: "📢", label: "loudspeaker announce" },
  { emoji: "📣", label: "megaphone announce" },
  { emoji: "📭", label: "empty inbox" },
  { emoji: "📬", label: "mailbox with mail" },
  { emoji: "📪", label: "closed mailbox" },
  { emoji: "🕐", label: "one clock" },
  { emoji: "🕘", label: "nine clock" },
  { emoji: "✅", label: "done complete" },
  { emoji: "🚩", label: "triangular flag milestone" },
  { emoji: "🎯", label: "target goal okr" },
  { emoji: "🏁", label: "checkered flag finish" },
  { emoji: "🥅", label: "goal net" },
  { emoji: "🔥", label: "fire hot trending popular" },
  { emoji: "🚨", label: "emergency urgent" },
  { emoji: "🚀", label: "fast growth" },
  { emoji: "🐌", label: "snail slow" },
  { emoji: "🐢", label: "turtle slow load" },
  { emoji: "🐇", label: "rabbit fast" },
  { emoji: "🐎", label: "horse fast" },
  { emoji: "📊", label: "dashboard" },
  // ── Communication / people ────────────────────────────────────────
  { emoji: "💬", label: "speech balloon chat" },
  { emoji: "💭", label: "thought balloon" },
  { emoji: "🗨️", label: "left speech balloon" },
  { emoji: "🗯️", label: "anger right bubble" },
  { emoji: "💌", label: "love letter" },
  { emoji: "📧", label: "e-mail mail" },
  { emoji: "📩", label: "incoming envelope" },
  { emoji: "📨", label: "incoming envelope signal" },
  { emoji: "📤", label: "outbox tray" },
  { emoji: "📥", label: "inbox tray" },
  { emoji: "📮", label: "postbox mail" },
  { emoji: "📞", label: "telephone receiver" },
  { emoji: "☎️", label: "telephone" },
  { emoji: "📱", label: "mobile phone" },
  { emoji: "📲", label: "mobile with arrow" },
  { emoji: "📳", label: "vibration mode" },
  { emoji: "👥", label: "busts silhouette team" },
  { emoji: "👤", label: "bust silhouette user" },
  { emoji: "🧑‍🤝‍🧑", label: "people holding hands team" },
  { emoji: "👨‍👩‍👧", label: "family" },
  { emoji: "👑", label: "crown admin" },
  { emoji: "🫂", label: "people hugging" },
  { emoji: "🤝", label: "handshake" },
  { emoji: "💪", label: "flexed biceps strong effort" },
  { emoji: "🗳️", label: "voting" },
  { emoji: "🙋", label: "raising hand ask" },
  { emoji: "🙌", label: "raising hands praise" },
  { emoji: "👏", label: "clapping hands applause" },
  { emoji: "👍", label: "thumbs up like approve" },
  { emoji: "👎", label: "thumbs down unlike" },
  { emoji: "🙏", label: "folded hands thanks" },
  // ── Design / creative / media ─────────────────────────────────────
  { emoji: "🎨", label: "artist palette design ui" },
  { emoji: "🖌️", label: "paintbrush design" },
  { emoji: "🖍️", label: "crayon" },
  { emoji: "✏️", label: "pencil edit" },
  { emoji: "🖊️", label: "pen" },
  { emoji: "🖋️", label: "fountain pen" },
  { emoji: "✒️", label: "black nib write" },
  { emoji: "🖼️", label: "framed picture image" },
  { emoji: "🎬", label: "clapper board video film" },
  { emoji: "🎥", label: "movie camera video" },
  { emoji: "📷", label: "camera photo" },
  { emoji: "📸", label: "camera with flash" },
  { emoji: "🎞️", label: "film frames media" },
  { emoji: "📺", label: "television video" },
  { emoji: "📻", label: "radio audio podcast" },
  { emoji: "🎧", label: "headphone audio" },
  { emoji: "🎵", label: "musical note music audio" },
  { emoji: "🎶", label: "musical notes song" },
  { emoji: "🎙️", label: "studio microphone podcast" },
  { emoji: "🔊", label: "speaker high volume" },
  { emoji: "🔈", label: "speaker low volume" },
  { emoji: "🎮", label: "video game game" },
  { emoji: "🕹️", label: "joystick game" },
  { emoji: "👾", label: "alien monster game" },
  { emoji: "🎲", label: "game die random" },
  { emoji: "🧩", label: "puzzle widget" },
  { emoji: "🎭", label: "performing arts" },
  { emoji: "🎪", label: "circus tent" },
  { emoji: "🎡", label: "ferris wheel" },
  { emoji: "🎠", label: "carousel horse" },
  { emoji: "💫", label: "dizzy rotate animate" },
  { emoji: "🌟", label: "glowing star highlight" },
  { emoji: "⭐", label: "star rating" },
  { emoji: "✨", label: "sparkles glow special" },
  { emoji: "💡", label: "light bulb idea" },
  { emoji: "🔦", label: "flashlight" },
  { emoji: "🔥", label: "hot" },
  // ── Science / math / engineering ──────────────────────────────────
  { emoji: "🔬", label: "microscope science" },
  { emoji: "🧬", label: "dna biology genome" },
  { emoji: "⚗️", label: "alembic chemistry" },
  { emoji: "🧪", label: "test tube chemistry lab" },
  { emoji: "🧫", label: "petri dish bio" },
  { emoji: "🌡️", label: "thermometer temperature" },
  { emoji: "🔭", label: "telescope astro" },
  { emoji: "🔢", label: "input numbers math" },
  { emoji: "🔣", label: "input symbols" },
  { emoji: "🔤", label: "input latin letters" },
  { emoji: "🔠", label: "input uppercase" },
  { emoji: "♾️", label: "infinity" },
  { emoji: "➕", label: "plus add" },
  { emoji: "➖", label: "minus subtract" },
  { emoji: "✖️", label: "multiply" },
  { emoji: "➗", label: "divide" },
  { emoji: "🧮", label: "abacus" },
  { emoji: "📐", label: "geometry" },
  { emoji: "⚙️", label: "mechanical" },
  // ── Nature / environment / places ─────────────────────────────────
  { emoji: "🌱", label: "seedling growth greenfield" },
  { emoji: "🌳", label: "deciduous tree" },
  { emoji: "🌴", label: "palm tree" },
  { emoji: "🌿", label: "herb green" },
  { emoji: "🍀", label: "four leaf clover luck" },
  { emoji: "🍃", label: "leaf fluttering" },
  { emoji: "🍄", label: "mushroom" },
  { emoji: "🌾", label: "sheaf of rice" },
  { emoji: "🌵", label: "cactus" },
  { emoji: "🪴", label: "potted plant" },
  { emoji: "🏔️", label: "snow capped mountain" },
  { emoji: "⛰️", label: "mountain" },
  { emoji: "🌋", label: "volcano" },
  { emoji: "🏝️", label: "desert island" },
  { emoji: "🏖️", label: "beach umbrella" },
  { emoji: "🌊", label: "water wave" },
  { emoji: "💧", label: "droplet water" },
  { emoji: "🌬️", label: "wind face" },
  { emoji: "🌈", label: "rainbow" },
  { emoji: "☀️", label: "sun sunny" },
  { emoji: "🌞", label: "sun with face" },
  { emoji: "🌙", label: "crescent moon" },
  { emoji: "🌝", label: "full moon face" },
  { emoji: "🌛", label: "first quarter moon" },
  { emoji: "🌠", label: "shooting star" },
  { emoji: "🪐", label: "ringed planet space" },
  { emoji: "🌌", label: "milky way night" },
  { emoji: "🌍", label: "earth" },
  { emoji: "🧊", label: "ice cube" },
  { emoji: "🌶️", label: "hot pepper" },
  // ── Places / buildings / transport ────────────────────────────────
  { emoji: "🏠", label: "house home" },
  { emoji: "🏡", label: "house with garden" },
  { emoji: "🏢", label: "office building corporate" },
  { emoji: "🏬", label: "department store" },
  { emoji: "🏭", label: "factory" },
  { emoji: "🏗️", label: "construction site" },
  { emoji: "🏰", label: "castle" },
  { emoji: "🏯", label: "japanese castle" },
  { emoji: "🏥", label: "hospital health" },
  { emoji: "🏫", label: "school education" },
  { emoji: "🏛️", label: "classical building landmark" },
  { emoji: "🛖", label: "hut" },
  { emoji: "🗼", label: "tokyo tower" },
  { emoji: "🗽", label: "statue of liberty" },
  { emoji: "⛲", label: "fountain" },
  { emoji: "🌉", label: "bridge at night" },
  { emoji: "🗺️", label: "world map" },
  { emoji: "🧭", label: "compass" },
  { emoji: "✈️", label: "airplane" },
  { emoji: "🚀", label: "rocket" },
  { emoji: "🛸", label: "flying saucer" },
  { emoji: "🚗", label: "car" },
  { emoji: "🚕", label: "taxi" },
  { emoji: "🚌", label: "bus" },
  { emoji: "🚲", label: "bicycle" },
  { emoji: "🚄", label: "high speed train" },
  { emoji: "🚢", label: "ship" },
  { emoji: "⛵", label: "sailboat" },
  { emoji: "⚓", label: "anchor" },
  { emoji: "🚁", label: "helicopter" },
  { emoji: "🛩️", label: "small airplane" },
  { emoji: "🚉", label: "station" },
  // ── Status / activity / misc ──────────────────────────────────────
  { emoji: "❓", label: "question help" },
  { emoji: "❗", label: "exclamation important" },
  { emoji: "💥", label: "collision crash" },
  { emoji: "💢", label: "anger" },
  { emoji: "🔍", label: "magnifying glass tilted search" },
  { emoji: "🔎", label: "magnifying glass search" },
  { emoji: "🧭", label: "orient compass" },
  { emoji: "📨", label: "receive" },
  { emoji: "🔄", label: "counterclockwise arrows sync" },
  { emoji: "🔁", label: "repeat loop" },
  { emoji: "🔃", label: "clockwise vertical arrows sync" },
  { emoji: "🆕", label: "new" },
  { emoji: "🆙", label: "up" },
  { emoji: "🆒", label: "cool" },
  { emoji: "🆓", label: "free" },
  { emoji: "🆖", label: "ng" },
  { emoji: "🆗", label: "ok" },
  { emoji: "🆘", label: "sos help" },
  { emoji: "🏴", label: "flag" },
  { emoji: "🚩", label: "flag mark" },
  { emoji: "⚽", label: "soccer ball" },
  { emoji: "🏀", label: "basketball" },
  { emoji: "🎾", label: "tennis" },
  { emoji: "🏐", label: "volleyball" },
  { emoji: "🏈", label: "american football" },
  { emoji: "🎳", label: "bowling" },
  { emoji: "🎿", label: "skis" },
  { emoji: "🤿", label: "diving mask" },
  { emoji: "🏆", label: "trophy award win" },
  { emoji: "🥇", label: "gold medal first" },
  { emoji: "🥈", label: "silver medal second" },
  { emoji: "🥉", label: "bronze medal third" },
  { emoji: "🎖️", label: "military medal" },
  { emoji: "🏅", label: "sports medal achievement" },
  { emoji: "📣", label: "megaphone announcement" },
  { emoji: "🧭", label: "navigate compass" },
  { emoji: "🗿", label: "moai statue" },
  { emoji: "⚗️", label: "beaker" },
  // ── Animals ───────────────────────────────────────────────────────
  { emoji: "🐻", label: "bear" },
  { emoji: "🐼", label: "panda" },
  { emoji: "🦊", label: "fox" },
  { emoji: "🐺", label: "wolf" },
  { emoji: "🐱", label: "cat" },
  { emoji: "🐶", label: "dog" },
  { emoji: "🐰", label: "rabbit" },
  { emoji: "🦊", label: "fox craft" },
  { emoji: "🦁", label: "lion" },
  { emoji: "🐯", label: "tiger" },
  { emoji: "🦓", label: "zebra" },
  { emoji: "🦒", label: "giraffe" },
  { emoji: "🦛", label: "hippopotamus" },
  { emoji: "🐘", label: "elephant" },
  { emoji: "🦏", label: "rhinoceros" },
  { emoji: "🐫", label: "camel" },
  { emoji: "🦙", label: "llama" },
  { emoji: "🐪", label: "two hump camel" },
  { emoji: "🦘", label: "kangaroo" },
  { emoji: "🦡", label: "badger" },
  { emoji: "🦨", label: "skunk" },
  { emoji: "🦥", label: "sloth" },
  { emoji: "🦦", label: "otter" },
  { emoji: "🦫", label: "beaver" },
  { emoji: "🦬", label: "bison" },
  { emoji: "🐄", label: "cow" },
  { emoji: "🐂", label: "ox" },
  { emoji: "🐃", label: "water buffalo" },
  { emoji: "🐎", label: "horse" },
  { emoji: "🐖", label: "pig" },
  { emoji: "🐏", label: "ram sheep" },
  { emoji: "🐑", label: "ewe sheep" },
  { emoji: "🐐", label: "goat" },
  { emoji: "🐵", label: "monkey face" },
  { emoji: "🐒", label: "monkey" },
  { emoji: "🦍", label: "gorilla" },
  { emoji: "🦧", label: "orangutan" },
  { emoji: "🐶", label: "puppy" },
  { emoji: "🐕", label: "dog breed" },
  { emoji: "🐩", label: "poodle" },
  { emoji: "🦮", label: "guide dog" },
  { emoji: "🐈", label: "cat breed" },
  { emoji: "🐆", label: "leopard" },
  { emoji: "🐅", label: "tiger whole" },
  { emoji: "🐊", label: "crocodile" },
  { emoji: "🐢", label: "turtle" },
  { emoji: "🦎", label: "lizard" },
  { emoji: "🐍", label: "snake" },
  { emoji: "🐉", label: "dragon" },
  { emoji: "🦕", label: "sauropod dinosaur" },
  { emoji: "🦖", label: "t rex dinosaur" },
  { emoji: "🐸", label: "frog" },
  { emoji: "🦄", label: "unicorn" },
  { emoji: "🐧", label: "penguin" },
  { emoji: "🐦", label: "bird" },
  { emoji: "🐤", label: "baby chick" },
  { emoji: "🦅", label: "eagle" },
  { emoji: "🦆", label: "duck" },
  { emoji: "🦢", label: "swan" },
  { emoji: "🦉", label: "owl" },
  { emoji: "🦩", label: "flamingo" },
  { emoji: "🦚", label: "peacock" },
  { emoji: "🦜", label: "parrot" },
  { emoji: "🐔", label: "chicken" },
  { emoji: "🐓", label: "rooster" },
  { emoji: "🦃", label: "turkey" },
  { emoji: "🐳", label: "whale spouting" },
  { emoji: "🐋", label: "whale" },
  { emoji: "🐬", label: "dolphin" },
  { emoji: "🦭", label: "seal" },
  { emoji: "🐊", label: "alligator" },
  { emoji: "🐟", label: "fish" },
  { emoji: "🐠", label: "tropical fish" },
  { emoji: "🐡", label: "blowfish puffer" },
  { emoji: "🦈", label: "shark" },
  { emoji: "🐙", label: "octopus" },
  { emoji: "🦑", label: "squid" },
  { emoji: "🦞", label: "lobster" },
  { emoji: "🦀", label: "crab" },
  { emoji: "🦐", label: "shrimp" },
  { emoji: "🐌", label: "snail" },
  { emoji: "🦋", label: "butterfly" },
  { emoji: "🐛", label: "bug" },
  { emoji: "🐜", label: "ant" },
  { emoji: "🐝", label: "honeybee" },
  { emoji: "🪲", label: "beetle" },
  { emoji: "🦗", label: "cricket" },
  { emoji: "🕷️", label: "spider" },
  { emoji: "🦂", label: "scorpion" },
  { emoji: "🪰", label: "fly" },
  { emoji: "🪳", label: "cockroach" },
  { emoji: "🦟", label: "mosquito" },
  { emoji: "🦠", label: "microbe" },
  // ── Food & drink ──────────────────────────────────────────────────
  { emoji: "🍎", label: "apple" },
  { emoji: "🍏", label: "green apple" },
  { emoji: "🍊", label: "orange citrus" },
  { emoji: "🍋", label: "lemon" },
  { emoji: "🍒", label: "cherries" },
  { emoji: "🍓", label: "strawberry" },
  { emoji: "🫐", label: "blueberries" },
  { emoji: "🍇", label: "grapes" },
  { emoji: "🍉", label: "watermelon" },
  { emoji: "🍑", label: "peach" },
  { emoji: "🥭", label: "mango" },
  { emoji: "🍍", label: "pineapple" },
  { emoji: "🥥", label: "coconut" },
  { emoji: "🥝", label: "kiwi" },
  { emoji: "🍌", label: "banana" },
  { emoji: "🥑", label: "avocado" },
  { emoji: "🍆", label: "eggplant" },
  { emoji: "🥦", label: "broccoli" },
  { emoji: "🥕", label: "carrot" },
  { emoji: "🌽", label: "corn" },
  { emoji: "🍞", label: "bread" },
  { emoji: "🥐", label: "croissant" },
  { emoji: "🥯", label: "bagel" },
  { emoji: "🧀", label: "cheese" },
  { emoji: "🥚", label: "egg" },
  { emoji: "🍳", label: "cooking egg" },
  { emoji: "🥓", label: "bacon" },
  { emoji: "🍗", label: "poultry leg" },
  { emoji: "🥩", label: "steak" },
  { emoji: "🍔", label: "hamburger" },
  { emoji: "🍟", label: "french fries" },
  { emoji: "🍕", label: "pizza" },
  { emoji: "🌭", label: "hot dog" },
  { emoji: "🥪", label: "sandwich" },
  { emoji: "🌮", label: "taco" },
  { emoji: "🌯", label: "burrito" },
  { emoji: "🥙", label: "stuffed flatbread" },
  { emoji: "🥗", label: "green salad" },
  { emoji: "🍿", label: "popcorn" },
  { emoji: "🍜", label: "steaming bowl noodles" },
  { emoji: "🍣", label: "sushi" },
  { emoji: "🍱", label: "bento box" },
  { emoji: "🍰", label: "shortcake" },
  { emoji: "🍦", label: "soft ice cream" },
  { emoji: "🍩", label: "doughnut" },
  { emoji: "🍪", label: "cookie" },
  { emoji: "🧁", label: "cupcake" },
  { emoji: "☕", label: "coffee" },
  { emoji: "🍵", label: "teacup tea" },
  { emoji: "🫖", label: "teapot" },
  { emoji: "🍺", label: "beer mug" },
  { emoji: "🍷", label: "wine glass" },
  { emoji: "🍸", label: "cocktail glass" },
  { emoji: "🥤", label: "cup with straw" },
  { emoji: "🧊", label: "ice cube" },
  // ── Symbols / shapes / status ─────────────────────────────────────
  { emoji: "🔴", label: "red circle status" },
  { emoji: "🟠", label: "orange circle" },
  { emoji: "🟡", label: "yellow circle" },
  { emoji: "🟢", label: "green circle status" },
  { emoji: "🔵", label: "blue circle" },
  { emoji: "🟣", label: "purple circle" },
  { emoji: "⚪", label: "white circle" },
  { emoji: "⚫", label: "black circle" },
  { emoji: "🟤", label: "brown circle" },
  { emoji: "🔴", label: "record status" },
  { emoji: "🟥", label: "red square" },
  { emoji: "🟧", label: "orange square" },
  { emoji: "🟨", label: "yellow square" },
  { emoji: "🟩", label: "green square status" },
  { emoji: "🟦", label: "blue square" },
  { emoji: "🟪", label: "purple square" },
  { emoji: "⬛", label: "black large square" },
  { emoji: "⬜", label: "white large square" },
  { emoji: "🟫", label: "brown square" },
  { emoji: "🔶", label: "large orange diamond" },
  { emoji: "🔷", label: "large blue diamond" },
  { emoji: "🔸", label: "small orange diamond" },
  { emoji: "🔹", label: "small blue diamond" },
  { emoji: "💠", label: "diamond with dot" },
  { emoji: "🔺", label: "red triangle upward" },
  { emoji: "🔻", label: "red triangle down" },
  { emoji: "◼️", label: "black medium square" },
  { emoji: "◻️", label: "white medium square" },
  { emoji: "▪️", label: "black small square" },
  { emoji: "▫️", label: "white small square" },
  { emoji: "✴️", label: "eight pointed star" },
  { emoji: "❇️", label: "sparkle" },
  { emoji: "🈯", label: "finger" },
  { emoji: "🅰️", label: "a" },
  { emoji: "🅱️", label: "b" },
  { emoji: "Ⓜ️", label: "m" },
  { emoji: "™️", label: "tm trademark" },
  // ── Professions / roles / people ──────────────────────────────────
  { emoji: "👩‍🔬", label: "woman scientist" },
  { emoji: "👨‍🔬", label: "man scientist" },
  { emoji: "🧑‍🔬", label: "scientist researcher" },
  { emoji: "👩‍🏫", label: "woman teacher" },
  { emoji: "👨‍🏫", label: "man teacher" },
  { emoji: "👩‍🎓", label: "woman student graduate" },
  { emoji: "👨‍🎓", label: "man student graduate" },
  { emoji: "👩‍⚖️", label: "woman judge" },
  { emoji: "👨‍⚖️", label: "man judge" },
  { emoji: "👩‍🎨", label: "woman artist" },
  { emoji: "👨‍🎨", label: "man artist" },
  { emoji: "👩‍✈️", label: "woman pilot" },
  { emoji: "👨‍✈️", label: "man pilot" },
  { emoji: "👩‍🚀", label: "woman astronaut" },
  { emoji: "👨‍🚀", label: "man astronaut" },
  { emoji: "👩‍🚒", label: "woman firefighter" },
  { emoji: "👨‍🚒", label: "man firefighter" },
  { emoji: "🕵️", label: "detective spy" },
  { emoji: "💂", label: "guard" },
  { emoji: "👷", label: "construction worker" },
  { emoji: "👮", label: "police officer" },
  { emoji: "🕴️", label: "businessman" },
  { emoji: "🧑‍🏭", label: "factory worker" },
  { emoji: "🧑‍⚕️", label: "health worker doctor" },
  { emoji: "🧑‍🔧", label: "mechanic technician" },
  { emoji: "🧑‍🍳", label: "chef cook" },
  { emoji: "🧑‍🌾", label: "farmer" },
  { emoji: "🧑‍🎤", label: "singer" },
  { emoji: "🧑‍🎄", label: "elf" },
  { emoji: "🧙", label: "mage wizard" },
  { emoji: "🧝", label: "elf fantasy" },
  { emoji: "🧛", label: "vampire" },
  { emoji: "🧚", label: "fairy" },
  { emoji: "🧜", label: "mermaid" },
  { emoji: "🤴", label: "prince" },
  { emoji: "👸", label: "princess" },
  // ── Electronics / gadgets / hardware ──────────────────────────────
  { emoji: "⌚", label: "watch wearable" },
  { emoji: "📟", label: "pager" },
  { emoji: "📠", label: "fax machine" },
  { emoji: "📹", label: "video camera" },
  { emoji: "🎥", label: "movie camera" },
  { emoji: "📷", label: "camera" },
  { emoji: "📸", label: "camera flash" },
  { emoji: "🖥️", label: "desktop" },
  { emoji: "💻", label: "laptop computer" },
  { emoji: "⌨️", label: "keyboard" },
  { emoji: "🖱️", label: "mouse" },
  { emoji: "🖨️", label: "printer" },
  { emoji: "🖲️", label: "trackball" },
  { emoji: "💾", label: "floppy" },
  { emoji: "📀", label: "dvd" },
  { emoji: "💿", label: "cd" },
  { emoji: "🎬", label: "film studio" },
  { emoji: "🎞️", label: "film frames" },
  { emoji: "🤳", label: "selfie" },
  { emoji: "🗜️", label: "compression" },
  { emoji: "⚗️", label: "distillation" },
  // ── Clothing / accessories ────────────────────────────────────────
  { emoji: "👕", label: "t shirt" },
  { emoji: "👖", label: "jeans" },
  { emoji: "🧥", label: "coat" },
  { emoji: "🧤", label: "gloves" },
  { emoji: "🧣", label: "scarf" },
  { emoji: "🥾", label: "hiking boot" },
  { emoji: "👟", label: "sneaker" },
  { emoji: "👒", label: "womans hat" },
  { emoji: "🧢", label: "billed cap" },
  { emoji: "🎩", label: "top hat" },
  { emoji: "👑", label: "crown" },
  { emoji: "👓", label: "glasses" },
  { emoji: "🕶️", label: "sunglasses" },
  { emoji: "🥽", label: "goggles" },
  // ── Music / media / instruments ───────────────────────────────────
  { emoji: "🎧", label: "headphone" },
  { emoji: "🎸", label: "guitar" },
  { emoji: "🎹", label: "musical keyboard" },
  { emoji: "🎻", label: "violin" },
  { emoji: "🎺", label: "trumpet" },
  { emoji: "🎷", label: "saxophone" },
  { emoji: "🥁", label: "drum" },
  { emoji: "🎤", label: "microphone" },
  // ── Activities / hobbies / sports ─────────────────────────────────
  { emoji: "🏃", label: "running" },
  { emoji: "🧗", label: "climbing" },
  { emoji: "🏊", label: "swimming" },
  { emoji: "🚴", label: "cycling" },
  { emoji: "🏋️", label: "lifting weights" },
  { emoji: "🧘", label: "meditation" },
  { emoji: "🎣", label: "fishing" },
  { emoji: "🛹", label: "skateboard" },
  { emoji: "🛼", label: "roller skate" },
  { emoji: "🏕️", label: "camping" },
  { emoji: "🧗‍♀️", label: "rock climbing" },
  { emoji: "🚵", label: "mountain biking" },
  { emoji: "🏄", label: "surfing" },
  { emoji: "🎿", label: "skiing" },
  { emoji: "🏒", label: "ice hockey" },
  { emoji: "🏓", label: "ping pong" },
  { emoji: "🏸", label: "badminton" },
  { emoji: "🥋", label: "martial arts" },
  // ── Objects / home / misc ─────────────────────────────────────────
  { emoji: "🛎️", label: "bellhop" },
  { emoji: "🪞", label: "mirror" },
  { emoji: "🪟", label: "window" },
  { emoji: "🛋️", label: "couch" },
  { emoji: "🛏️", label: "bed" },
  { emoji: "🚪", label: "door" },
  { emoji: "🪑", label: "chair" },
  { emoji: "🛁", label: "bathtub" },
  { emoji: "🚿", label: "shower" },
  { emoji: "🧹", label: "broom clean" },
  { emoji: "🧺", label: "basket laundry" },
  { emoji: "🪣", label: "bucket" },
  { emoji: "🧽", label: "sponge" },
  { emoji: "🧴", label: "lotion" },
  { emoji: "🧸", label: "teddy bear" },
  { emoji: "🎈", label: "balloon" },
  { emoji: "🎉", label: "party popper" },
  { emoji: "🎊", label: "confetti ball" },
  { emoji: "🎎", label: "dolls" },
  { emoji: "🎐", label: "wind chime" },
  { emoji: "🎏", label: "carp streamer" },
  { emoji: "🪁", label: "kite" },
  { emoji: "🛷", label: "sled" },
  { emoji: "🎂", label: "birthday cake" },
  { emoji: "🎄", label: "christmas" },
  { emoji: "🕯️", label: "candle" },
  { emoji: "💍", label: "ring" },
  { emoji: "🔮", label: "crystal ball" },
  { emoji: "🧿", label: "nazar" },
  { emoji: "🌸", label: "cherry blossom" },
  { emoji: "💐", label: "bouquet" },
  { emoji: "🪄", label: "magic wand" },
];
