import type { ComponentType } from "react";
import {
  AlertIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BracesIcon,
  BookIcon,
  CanvasIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChipIcon,
  CloseIcon,
  ConversationTreeGlyphIcon,
  ClockIcon,
  CopyIcon,
  EditIcon,
  ExternalLinkIcon,
  FolderIcon,
  GearIcon,
  GitDiffGlyphIcon,
  GlobeIcon,
  JsonIcon,
  LanguageIcon,
  LlmAuditGlyphIcon,
  MinusIcon,
  MoonIcon,
  PanelRightIcon,
  PlusIcon,
  RefreshIcon,
  RssIcon,
  SearchIcon,
  SidebarIcon,
  SparkleIcon,
  StarIcon,
  StopIcon,
  SunIcon,
  TerminalGlyphIcon,
  TokensChartIcon,
  ToolIcon,
  TrashIcon,
} from "./primitives";
import {
  ConversationTreeIcon,
  GitDiffIcon,
  JsonBracesIcon,
  SettingsIcon,
  TerminalIcon,
  TokensIcon,
  TranslateIcon,
  WrenchIcon,
} from "./animated";

/**
 * 基础静态图标 registry。
 *
 * 约定：业务组件优先通过这个 registry 取基础图标；需要 hover/path 动画
 * 的图标使用 ANIMATED_ICONS；文件和 Provider 图标使用 domains.ts 的领域 API。
 */
export const ICONS = {
  alert: AlertIcon,
  arrowLeft: ArrowLeftIcon,
  book: BookIcon,
  canvas: CanvasIcon,
  arrowRight: ArrowRightIcon,
  braces: BracesIcon,
  calendar: CalendarIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chip: ChipIcon,
  close: CloseIcon,
  clock: ClockIcon,
  copy: CopyIcon,
  conversationTree: ConversationTreeGlyphIcon,
  edit: EditIcon,
  externalLink: ExternalLinkIcon,
  folder: FolderIcon,
  gear: GearIcon,
  gitDiff: GitDiffGlyphIcon,
  globe: GlobeIcon,
  json: JsonIcon,
  language: LanguageIcon,
  llmAudit: LlmAuditGlyphIcon,
  minus: MinusIcon,
  moon: MoonIcon,
  panelRight: PanelRightIcon,
  plus: PlusIcon,
  refresh: RefreshIcon,
  rss: RssIcon,
  search: SearchIcon,
  sidebar: SidebarIcon,
  sparkle: SparkleIcon,
  star: StarIcon,
  stop: StopIcon,
  tokens: TokensChartIcon,
  sun: SunIcon,
  terminal: TerminalGlyphIcon,
  tool: ToolIcon,
  trash: TrashIcon,
} as const satisfies Record<string, ComponentType<never>>;

export const ANIMATED_ICONS = {
  conversationTree: ConversationTreeIcon,
  gitDiff: GitDiffIcon,
  jsonBraces: JsonBracesIcon,
  settings: SettingsIcon,
  terminal: TerminalIcon,
  tokens: TokensIcon,
  translate: TranslateIcon,
  wrench: WrenchIcon,
} as const;

export type IconName = keyof typeof ICONS;
export type AnimatedIconName = keyof typeof ANIMATED_ICONS;
