export const TOOL_MARKET_IDS = ["agent_todo", "show_media", "ask_user_questions", "user_todos_list", "user_todo_description", "pi_work_get_active_sessions_id", "pi_work_get_session_info_by_id"] as const;
export type ToolMarketId = (typeof TOOL_MARKET_IDS)[number];
export type ToolMarketCategory = "agent" | "user_todo";
export interface ToolMarketDefinition { id: ToolMarketId; name: string; category: ToolMarketCategory; description: string; parameters: Record<string, unknown>; returns: Record<string, unknown> | null; promptSnippet: string | null; promptGuidelines: string[]; systemPrompt: string | null; }
const object = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", properties, required, additionalProperties: false });
const string = (description: string) => ({ type: "string", description });
const number = (description: string) => ({ type: "number", description });

export const TOOL_MARKET_DEFINITIONS: ToolMarketDefinition[] = [
  { id: "agent_todo", name: "Agent Todo", category: "agent", description: "Track a small task list for multi-step work. Each task has a subject, an optional description, and one of three statuses: pending, in_progress, or completed.", parameters: object({ action: { type: "string", enum: ["create", "update", "list", "delete", "clear"], description: "Operation to perform." }, subject: string("Task title for create, or updated title for update."), description: string("Long-form description for create or update."), id: number("Task id for update or delete."), status: { type: "string", enum: ["pending", "in_progress", "completed"], description: "Target status for update." } }, ["action"]), returns: object({ kind: string("Result kind."), state: object({ tasks: { type: "array" }, nextId: number("Next task id.") }) }), promptSnippet: "Track a small task list for multi-step work.", promptGuidelines: [], systemPrompt: "## Tool agent_todo guidelines\n- Use agent_todo for complex work with 5+ steps or when the user gives a long task list. Skip trivial or conversational requests.\n- Figure out what you really need to do before creating tasks list. Sometimes you need to research and explore the codebase first.\n- Mark tasks in_progress before starting them and completed when done.\n- Use create, update, list, delete, and clear as appropriate.\n- Before finishing work, use agent_todo list to check task status and mark completed tasks." },
  { id: "show_media", name: "Show Media", category: "agent", description: "Display up to 5 multimedia files (images, video, audio) in the Pi Work UI.", parameters: object({ paths: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 5, description: "Paths to image, video, or audio files." } }, ["paths"]), returns: object({ files: { type: "array" }, summary: { type: "string" } }), promptSnippet: "Render images, video, and audio files inline in the chat UI.", promptGuidelines: ["When your work output includes audio, video, or images, use the show_media tool to present them to the user interface.", "show_media accepts up to 5 paths per call. Batch related artifacts into a single call when they belong together."], systemPrompt: null },
  { id: "ask_user_questions", name: "Ask User Questions", category: "agent", description: "Ask the user 1-5 multiple-choice questions and wait for their answers. Each question has 2-4 options; required questions are enabled by default and an Other option is added automatically.", parameters: object({ questions: { type: "array", minItems: 1, maxItems: 5, items: { type: "object", properties: { header: string("Short 1-12 character label."), question: string("Question shown to the user."), multiSelect: { type: "boolean" }, required: { type: "boolean" }, options: { type: "array", minItems: 2, maxItems: 4 } }, required: ["header", "question", "options"] } } }, ["questions"]), returns: object({ answers: { type: "array" }, cancelled: { type: "boolean" } }), promptSnippet: "Ask the user structured multiple-choice questions.", promptGuidelines: ["Use ask_user_questions when you need a decision from the user before continuing.", "Each call can carry 1-5 questions; group related decisions in one call.", "Each question must have 2-4 options.", "Set multiSelect true when multiple options are valid.", "Questions are required by default; use required false for optional questions.", "An Other option is appended automatically; do not add one yourself.", "Do not call this tool from a scheduled task or when no user is available."], systemPrompt: null },
  { id: "user_todos_list", name: "User Todos List", category: "user_todo", description: "Look up the user's pi-work todos and return a lightweight summary with status, tag, and time-window filters. Results are sorted with active priority first and include a truncated flag when the limit is exceeded.", parameters: object({ status: { type: "string", enum: ["done", "processing", "all"] }, tags: { type: "array", items: { type: "string" } }, create_time_window: { type: "object" }, due_time_window: { type: "object" }, limit: number("Maximum items to return; defaults to 50 and is capped at 200.") }), returns: object({ total: number("Total matching todos."), returned: number("Returned count."), truncated: { type: "boolean" }, todos: { type: "array" } }), promptSnippet: null, promptGuidelines: [], systemPrompt: null },
  { id: "user_todo_description", name: "User Todo Description", category: "user_todo", description: "Fetch the full description, completion note, embedded images, and completion time of a single todo by id. Returns a not_found error result when the id does not exist.", parameters: object({ id: { ...string("Todo id returned by user_todos_list."), minLength: 1 } }, ["id"]), returns: object({ content: string("Description HTML."), images: { type: "array" }, completion_note: string("Completion note HTML."), completion_images: { type: "array" }, completed_at: number("Completion time in epoch ms."), error: string("not_found when the todo does not exist.") }), promptSnippet: null, promptGuidelines: [], systemPrompt: null },
  { id: "pi_work_get_active_sessions_id", name: "Pi Work Active Sessions", category: "agent", description: "List the ids of sessions currently loaded in memory in Pi Work. Use a returned id with pi_work_get_session_info_by_id for detail.", parameters: object({}), returns: object({ sessionIds: { type: "array", items: { type: "string" } }, running: { type: "array", items: { type: "string" } }, count: number("Number of active sessions.") }), promptSnippet: "List active Pi Work session ids.", promptGuidelines: ["Call pi_work_get_active_sessions_id to enumerate sessions currently loaded in Pi Work, then use pi_work_get_session_info_by_id with a returned session id for detail.", "The result is a snapshot; a session that isn't in memory won't be listed."], systemPrompt: null },
  { id: "pi_work_get_session_info_by_id", name: "Pi Work Session Info", category: "agent", description: "Return a read-only disk-backed detail snapshot for one Pi Work session by id: sessionName, cwd, timestamps, messageCount, model, thinking level, first/last messages, aggregated token usage, compaction history, and live running state. Returns not_found when the id does not exist.", parameters: object({ sessionId: { ...string("Pi Work session id to inspect."), minLength: 1 } }, ["sessionId"]), returns: object({ sessionId: string("The requested id."), sessionName: string("Session display name."), cwd: string("Working directory."), created: string("Start time ISO."), modified: string("Last-modified ISO."), messageCount: number("Number of visible messages on the active branch."), model: object({ provider: string("Provider id."), modelId: string("Model id.") }), thinkingLevel: string("Thinking level."), firstUserMessage: string("First user message text."), lastAssistantMessage: string("Last assistant message text."), lastAssistantStatus: object({ stopReason: string("Stop reason."), error: string("Error message, if any.") }), totalUsage: object({ inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, cost: number("Total cost.") }), compaction: object({ count: number("Number of compaction points."), lastTokensBefore: number("Tokens before last compaction, or null."), lastSummary: string("Last compaction summary, or null.") }), parentSessionId: string("Parent session id, if any."), alive: { type: "boolean" }, running: { type: "boolean" }, error: string("not_found when the session does not exist.") }), promptSnippet: "Read details for one Pi Work session.", promptGuidelines: ["Get an id first with pi_work_get_active_sessions_id.", "This tool is read-only; it never modifies the session.", "Context window is not reported because it is not stored on disk."], systemPrompt: null },
];
