import { CODEGRAPH_TOOL_IDS } from "./codegraph-tool-ids";
import { MAX_CONCURRENT_SUBAGENT_RUNS } from "./types";

export const TOOL_MARKET_IDS = ["spawn_subagent", "show_media", "ask_user_questions", "celebrate", "web_search", "fetch_content", "pi_work_call", ...CODEGRAPH_TOOL_IDS] as const;
export type ToolMarketId = (typeof TOOL_MARKET_IDS)[number];
export type ToolMarketCategory = "coding" | "web" | "platform";
export interface ToolMarketDefinition { id: ToolMarketId; name: string; category: ToolMarketCategory; description: string; parameters: Record<string, unknown>; returns: Record<string, unknown> | null; promptSnippet: string | null; promptGuidelines: string[]; systemPrompt: string | null; }
const object = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", properties, required, additionalProperties: false });
const string = (description: string) => ({ type: "string", description });
const number = (description: string) => ({ type: "number", description });

// Shared append-block text shown for every codegraph_* entry in the Tool
// Market: the family is BOUND in the tool picker (TOOL_GROUPS — toggled
 // on/off as a group) and contributes ONE system-prompt block server-side
// (CODEGRAPH_SYSTEM_PROMPT_BLOCK in lib/server/codegraph-tool.ts). Keep the
// two texts in sync.
const CODEGRAPH_SHARED_SYSTEM_PROMPT = "## CodeGraph toolset guidelines\n- Prefer codegraph_* tools over raw read/grep for structural questions once a project is indexed.\n- For 'how does X work', 'flow from X to Y', or 'what is affected by editing X' — call `codegraph_explore` with the relevant symbol names before reaching for read/grep.\n- Treat source returned by `codegraph_explore` as already-read; don't re-read the same files separately.\n- If the response is insufficient, call it again with more specific symbol names rather than reconstructing the graph by hand.\n- If the project is not indexed, create the index with `codegraph_build` (mode=init) — the tool pauses for user confirmation before the heavy scan. Until it completes, keep using read/grep/ls.\n- sync keeps an already-indexed project fresh after many file changes and is safe to call on your own judgement; init (first build) and index (full rebuild) take minutes, pause for user confirmation, and stop if denied.";
export const TOOL_MARKET_DEFINITIONS: ToolMarketDefinition[] = [
  { id: "spawn_subagent", name: "Spawn Subagent", category: "coding", description: "Launch a persistent specialized subagent to handle a focused task. The subagent runs in the current working directory and returns an evidence-based conclusion. Use subagent_type=codebase_explorer to read and report on code, or subagent_type=code_reviewer to review code and report findings with file:line evidence.", parameters: object({ description: { ...string("A short 3-5 word description of the task"), minLength: 1, maxLength: 200 }, prompt: { ...string("The complete instructions for the subagent"), minLength: 1, maxLength: 50000 }, subagent_type: { type: "string", enum: ["codebase_explorer", "code_reviewer"], description: "Which subagent profile to use: codebase_explorer reads the codebase and reports what it finds; code_reviewer reviews code or a diff and reports evidence-backed findings (both are read-only and may inspect history and diffs with bash)." } }, ["description", "prompt", "subagent_type"]), returns: object({ taskId: string("Persistent subagent task id."), sessionId: string("Persistent child session id."), status: { type: "string", enum: ["completed", "failed", "cancelled"] }, description: string("The task description."), result: string("The subagent's final result."), error: string("Failure or cancellation message.") }), promptSnippet: "Launch a specialized subagent for a focused task.", promptGuidelines: [], systemPrompt: `## Tool spawn_subagent guidelines\n- For independent tasks that are parallelizable and have a well-defined scope, dispatch the tasks to subagents using \`spawn_subagent\`. Examples include codebase exploration, research and information gathering, and code review.\n- \`subagent_type\` selects the profile: \`codebase_explorer\` for read-only code exploration and reporting, \`code_reviewer\` for reviewing code or a diff and reporting evidence-backed findings. Both are read-only and may inspect history and diffs with bash.\n- When you need to explore the codebase, prioritize using the spawn_subagent tool to dispatch a codebase_explorer subagent for exploration, rather than doing it yourself.\n- When using codebase_explorer, assign it the purely code exploration and reporting task, without requiring it to give any suggestions—it is only a code retriever.\n- When using code_reviewer, hand it the change, files, or question to review plus the standards to judge against; it reports findings with file:line evidence and never edits the code.\n- Independent tasks can be dispatched together: emit several \`spawn_subagent\` calls in the same message instead of one per turn. Subagents run in parallel (at most ${MAX_CONCURRENT_SUBAGENT_RUNS} at a time, further calls wait for a free slot), so keep each task self-contained and do not make one depend on another's result.` },
  { id: "show_media", name: "Show Media", category: "platform", description: "Display up to 5 multimedia files (images, video, audio) in the Pi Work UI.", parameters: object({ paths: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 5, description: "Paths to image, video, or audio files." } }, ["paths"]), returns: object({ files: { type: "array" }, summary: { type: "string" } }), promptSnippet: "Render images, video, and audio files inline in the chat UI.", promptGuidelines: [], systemPrompt: "## Tool show_media guidelines\n- When your work output includes audio, video, or images, use the show_media tool to present them to the user interface.\n- show_media accepts up to 5 paths per call (image / video / audio only). Batch related artifacts into a single call when they belong together." },
  { id: "ask_user_questions", name: "Ask User Questions", category: "platform", description: "Ask the user 1-5 multiple-choice questions and wait for their answers. Each question has 2-4 options; required questions are enabled by default and an Other option is added automatically.", parameters: object({ questions: { type: "array", minItems: 1, maxItems: 5, items: { type: "object", properties: { header: string("Short 1-12 character label."), question: string("Question shown to the user."), multiSelect: { type: "boolean" }, required: { type: "boolean" }, options: { type: "array", minItems: 2, maxItems: 4 } }, required: ["header", "question", "options"] } } }, ["questions"]), returns: object({ answers: { type: "array" }, cancelled: { type: "boolean" } }), promptSnippet: "Ask the user structured multiple-choice questions.", promptGuidelines: [], systemPrompt: "## Tool ask_user_questions guidelines\n- Use ask_user_questions when you need a decision from the user before continuing.\n- Each call can carry 1-5 questions; group related decisions in one call.\n- Each question must have 2-4 options.\n- Set multiSelect true when multiple options are valid.\n- Questions are required by default; use required false for optional questions.\n- An Other option is appended automatically; do not add one yourself.\n- Do not call this tool from a scheduled task or when no user is available." },
  { id: "celebrate", name: "Celebrate", category: "platform", description: "Play a celebration animation in the Pi Work UI: confetti rain, party cannons, or both at once. Purely visual and returns instantly.", parameters: object({ style: { type: "string", enum: ["auto", "confetti", "cannon", "grand"], description: "Which effect to play; 'auto' (default) picks one at random, 'grand' plays confetti and cannons together." }, duration: number("Animation length in seconds, 1-15; defaults to 5.") }), returns: object({ style: string("Requested style."), resolvedStyle: string("Concrete effect resolved from 'auto'."), durationMs: number("Animation length in ms.") }), promptSnippet: "Play a confetti/cannon celebration animation in the UI.", promptGuidelines: [], systemPrompt: "## Tool celebrate guidelines\n- Use celebrate when a milestone is reached and it deserves a bit of joy: a big task finished, all tests passing, a successful deployment, a release shipped, or when the user asks to celebrate / 恭喜 / 庆祝.\n- Call it once per milestone — do not spam it after every minor step.\n- The tool returns instantly and never blocks; continue your reply right after calling it." },
  { id: "web_search", name: "Web Search", category: "web", description: "Search the web using Tavily and return a synthesized answer with source citations.", parameters: object({ query: string("Web search query."), numResults: number("Number of results, 1-20."), recencyFilter: string("day, week, month, or year."), domainFilter: { type: "array", items: { type: "string" } }, includeContent: { type: "boolean" } }, ["query"]), returns: object({ answer: string("Tavily answer."), results: { type: "array" }, inlineContent: { type: "array" } }), promptSnippet: "Search the web when current or external information is needed.", promptGuidelines: [], systemPrompt: "## Tool web_search guidelines\n- Use web_search for current facts, documentation, news, or information outside the workspace." },
  { id: "fetch_content", name: "Fetch Content", category: "web", description: "Fetch a public HTTP(S) URL and return readable Markdown or raw text.", parameters: object({ url: string("HTTP or HTTPS URL to fetch."), mode: { type: "string", enum: ["readable", "raw"] } }, ["url"]), returns: object({ url: string("Final URL."), title: string("Page title."), content: string("Fetched content."), contentType: string("Response content type."), status: number("HTTP status.") }), promptSnippet: "Fetch a web page when you need its full content.", promptGuidelines: [], systemPrompt: "## Tool fetch_content guidelines\n- Use fetch_content after web_search when source details are needed; use raw mode for APIs or exact text." },
  { id: "pi_work_call", name: "Pi Work Call", category: "platform", description: "Call Pi Work platform capabilities: list recent/active sessions and get a session detail snapshot by id. One dispatcher for pi-work platform operations.", parameters: object({ action: { type: "string", enum: ["list_recent_sessions", "list_active_sessions", "get_session_info"], description: "Which platform operation to perform." }, limit: number("list_recent_sessions only: number of sessions to return, 1-50, default 10."), sessionId: string("get_session_info only: the Pi Work session id to inspect.") }, ["action"]), returns: object({ action: string("The action performed.") }), promptSnippet: "Call Pi Work platform APIs: recent/active sessions and session detail.", promptGuidelines: [], systemPrompt: null },
  // ── CodeGraph tools (semantic code intelligence over the project index) ──
  // Backed by lib/server/codegraph-tool.ts, which drives the CodeGraph SDK's
  // MCP ToolHandler in-process (see codegraph-sdk.ts). All tools accept an
  // optional `path` that must resolve inside an allowed root. When the project
  // is not indexed they return guidance instead of failing hard.
  // The family is BOUND in the tool picker (TOOL_GROUPS: toggled on/off as a
  // group) and shares ONE append block (CODEGRAPH_SYSTEM_PROMPT_BLOCK) — the
  // identical systemPrompt shown below documents that shared block.
  { id: "codegraph_status", name: "CodeGraph Status", category: "coding", description: "Index health check: files / nodes / edges / database size / journal mode, plus node-kind and language breakdowns and pending-resolution warnings.", parameters: object({ path: string("Project root to query (the MCP `projectPath`): any directory inside the project works; defaults to the session cwd. Must resolve inside an allowed root (a session cwd or a pi-work workspace).") }), returns: object({ content: string("Markdown index-status report.") }), promptSnippet: "Check CodeGraph index status for a project.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_search", name: "CodeGraph Search", category: "coding", description: "Full-text search for indexed symbols: returns matching nodes with kind, qualified name, file path, and line numbers.", parameters: object({ query: string("Symbol name or search text."), path: string("Project root to query"), limit: number("Maximum results (1-100, default 10)."), kind: string("Filter by node kind: function, method, class, interface, type, variable, route, component.") }, ["query"]), returns: object({ results: number("Number of matches.") }), promptSnippet: "Search indexed symbols by name or text.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_explore", name: "CodeGraph Explore", category: "coding", description: "One-shot code exploration: given a symbol bag or a description, returns the relevant symbols' verbatim line-numbered source grouped by file, the call path among them, and blast radius. The primary codegraph tool — call it BEFORE read/grep for structural, flow, architecture, or modify-impact questions.", parameters: object({ query: string("Symbol bag or natural-language description of the area to explore."), path: string("Project root to query"), maxFiles: number("Maximum files to include source from (1-12, default 12).") }, ["query"]), returns: object({ content: string("Markdown exploration output.") }), promptSnippet: "Explore an area of the codebase: source + call paths in one call.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_node", name: "CodeGraph Node", category: "coding", description: "Two modes. (1) READ A FILE — pass `file` (path or basename) with no `symbol` and it returns that file's on-disk source with line numbers, narrowable with `offset`/`limit`, plus which files depend on it; `symbolsOnly` returns just the file's symbol map. (2) ONE SYMBOL — its location, signature and caller/callee trail in one call; pass `includeCode: true` for the verbatim body. An ambiguous name returns every matching definition (pass `file`/`line` to pin one).", parameters: object({ symbol: string("Symbol name (may be qualified, e.g. AgentSessionWrapper::sessionId). Omit and pass file to read a file."), includeCode: { type: "boolean", default: false, description: "Symbol mode: include the symbol's full body (default: false)." }, path: string("Project root to query"), file: string("Read this file instead (path or basename), or disambiguate an overloaded symbol to this file."), offset: number("File mode: 1-based line to start reading from (like Read's offset)."), limit: number("File mode: maximum lines to return (like Read's limit)."), symbolsOnly: { type: "boolean", default: false, description: "File mode: return just the symbol map + dependents instead of source." }, line: number("Symbol mode only: disambiguate to the definition at/around this line.") }), returns: object({ content: string("Markdown symbol/file detail output.") }), promptSnippet: "Read a single symbol's source with its call trails.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_callers", name: "CodeGraph Callers", category: "coding", description: "List every function/method that calls the given symbol, with file and line.", parameters: object({ symbol: string("Symbol name (may be qualified with :: or .)."), path: string("Project root to query"), limit: number("Maximum results (1-100, default 20).") }, ["symbol"]), returns: object({ count: number("Number of callers.") }), promptSnippet: "Find who calls a symbol.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_callees", name: "CodeGraph Callees", category: "coding", description: "List what the given symbol calls (its callees), with file and line.", parameters: object({ symbol: string("Symbol name (may be qualified with :: or .)."), path: string("Project root to query"), limit: number("Maximum results (1-100, default 20).") }, ["symbol"]), returns: object({ count: number("Number of callees.") }), promptSnippet: "Find what a symbol calls.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_impact", name: "CodeGraph Impact", category: "coding", description: "Analyze the blast radius of changing a symbol: every node reachable within a traversal depth plus the connecting edges.", parameters: object({ symbol: string("Symbol name whose blast radius to analyze."), path: string("Project root to query"), depth: number("Traversal depth (1-10, default 2).") }, ["symbol"]), returns: object({ nodeCount: number("Affected node count.") }), promptSnippet: "Analyze what code is affected by changing a symbol.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_files", name: "CodeGraph Files", category: "coding", description: "List the files CodeGraph has indexed with language and symbol counts (JSON), or a pretty tree/flat/grouped view.", parameters: object({ path: string("Project root to query"), filter: string("Only files under this directory, project-relative (the MCP `path` filter)."), pattern: string("Glob pattern, e.g. lib/**/*.ts."), format: string("Output format: tree, flat, grouped.") }), returns: object({ fileCount: number("Number of indexed files.") }), promptSnippet: "List indexed files with language and symbol counts.", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
  { id: "codegraph_build", name: "CodeGraph Build", category: "coding", description: "Build or update the CodeGraph index for a project: sync (incremental), index (full rebuild), or init (first build). The index is what the other codegraph_* tools query. init/index take minutes and require user confirmation.", parameters: object({ mode: { type: "string", enum: ["sync", "index", "init"], default: "sync", description: "sync (default, fast) / index (full rebuild, user-confirmed) / init (first build, user-confirmed)." }, path: string("Project root to build.") }), returns: object({ filesIndexed: number("Files indexed."), filesAdded: number("Files added (sync)."), filesModified: number("Files modified (sync)."), filesRemoved: number("Files removed (sync)."), fileCount: number("Index file count after build.") }), promptSnippet: "Build or update the CodeGraph index (sync / index / init).", promptGuidelines: [], systemPrompt: CODEGRAPH_SHARED_SYSTEM_PROMPT },
];
