// Types mirrored from pi-mono coding-agent session-manager

interface SessionEntryBase {
  type: string;
  id: string;
  parentId: string | null;
  timestamp: string;
}

export interface TextContent {
  type: "text";
  text: string;
}

export interface ImageContent {
  type: "image";
  source: {
    type: "base64" | "url";
    media_type?: string;
    data?: string;
    url?: string;
  };
}

export interface ThinkingContent {
  type: "thinking";
  thinking: string;
}

export interface ToolCallContent {
  type: "toolCall";
  toolCallId: string;
  toolName: string;
  input: Record<string, unknown>;
}

/** One file surfaced by a turn's `read` tool calls (footer chips). */
export interface ReadFileInfo {
  /** Absolute path (resolved from the tool input against the session cwd). */
  path: string;
  /** Basename shown on the chip. */
  name: string;
}

export type AssistantContentBlock = TextContent | ImageContent | ThinkingContent | ToolCallContent;

export interface UserMessage {
  role: "user";
  content: string | (TextContent | ImageContent)[];
  timestamp?: number;
}

export interface AssistantMessage {
  role: "assistant";
  content: AssistantContentBlock[];
  model: string;
  provider: string;
  stopReason?: string;
  errorMessage?: string;
  timestamp?: number;
  usage?: {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
    cost: {
      input: number;
      output: number;
      cacheRead: number;
      cacheWrite: number;
      total: number;
    };
  };
}

export interface ToolResultMessage {
  role: "toolResult";
  toolCallId: string;
  toolName?: string;
  content: (TextContent | ImageContent)[];
  isError?: boolean;
  timestamp?: number;
}

// ── Tool registry (shared by frontend types and rpc-manager) ──────────────
// Single source of truth: lib/types.ts. lib/pi-types.ts re-exports `ToolInfo`
// so the pi-SDK-shaped interface stays where the backend already imports it.

/** A tool registered by pi's resource loader — used to render the
 *  ChatInput tools checklist. Shape mirrors `inner.getAllTools()` from
 *  AgentSessionLike in lib/pi-types.ts. */
export interface ToolInfo {
  name: string;
  description: string;
}

/** The user's tool selection state for a session. `[]` ≡ "Off" (no tools);
 *  `"all"` ≡ "High" (every registered tool); a non-empty array ≡ "Custom".
 *  Matches the wire format of `set_tools` and `toolNames` in
 *  `POST /api/agent/new`, so the frontend serialises it directly. */
export type ToolSelection = string[] | "all";

export interface CustomMessage {
  role: "custom";
  customType: string;
  content: string | (TextContent | ImageContent)[];
  display: boolean;
  details?: unknown;
  timestamp?: number;
}

export type AgentMessage = UserMessage | AssistantMessage | ToolResultMessage | CustomMessage;

export interface SessionMessageEntry extends SessionEntryBase {
  type: "message";
  message: AgentMessage;
}

interface ThinkingLevelChangeEntry extends SessionEntryBase {
  type: "thinking_level_change";
  thinkingLevel: string;
}

interface ModelChangeEntry extends SessionEntryBase {
  type: "model_change";
  provider: string;
  modelId: string;
}

/** Mirrors `CompactionDetails` in `@earendil-works/pi-coding-agent/dist/core/compaction/compaction.d.ts`.
 *  Pi-generated entries always carry this shape; extension-generated ones use `details: unknown`. */
export interface CompactionEntryDetails {
  readFiles: string[];
  modifiedFiles: string[];
}

/** Mirrors `Usage` in `@earendil-works/pi-coding-agent/dist/core/compaction/compaction.d.ts`
 *  — the billing tokens for the LLM call that produced the summary. Optional in the
 *  on-disk entry: pi writes `usage` when the model returned token counts. */
export interface CompactionUsage {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  totalTokens: number;
  cost: { input: number; output: number; cacheRead: number; cacheWrite: number; total: number };
}

export interface CompactionEntry extends SessionEntryBase {
  type: "compaction";
  summary: string;
  firstKeptEntryId: string;
  tokensBefore: number;
  details?: CompactionEntryDetails | unknown;
  fromHook?: boolean;
  /** Provider usage for the summarization call. Only present when the summary
   *  was generated by a model that returned token counts. */
  usage?: CompactionUsage;
}

interface BranchSummaryEntry extends SessionEntryBase {
  type: "branch_summary";
  fromId: string;
  summary: string;
  details?: unknown;
  fromHook?: boolean;
}

interface CustomEntry extends SessionEntryBase {
  type: "custom";
  customType: string;
  data?: unknown;
}

interface CustomMessageEntry extends SessionEntryBase {
  type: "custom_message";
  customType: string;
  content: string | (TextContent | ImageContent)[];
  details?: unknown;
  display: boolean;
}

interface LabelEntry extends SessionEntryBase {
  type: "label";
  targetId: string;
  label: string | undefined;
}

interface SessionInfoEntry extends SessionEntryBase {
  type: "session_info";
  name?: string;
}

export type SessionEntry =
  | SessionMessageEntry
  | ThinkingLevelChangeEntry
  | ModelChangeEntry
  | CompactionEntry
  | BranchSummaryEntry
  | CustomEntry
  | CustomMessageEntry
  | LabelEntry
  | SessionInfoEntry;

export interface SessionTreeNode {
  entry: SessionEntry;
  children: SessionTreeNode[];
  label?: string;
}

export interface SessionInfo {
  path: string;
  id: string;
  cwd: string;
  name?: string;
  created: string;
  modified: string;
  messageCount: number;
  firstMessage: string;
  parentSessionId?: string; // read-only historical metadata — was set on
  // sessions created via the (now removed) fork feature. Preserved here so
  // old `.jsonl` files keep loading; the sidebar no longer uses it to
  // render any tree structure.
  // True while the agent is between agent_start and agent_end (or compacting).
  // Set by the read layer to false; the /api/sessions route enriches from the
  // wrapper registry.
  running: boolean;
}

export interface SessionContext {
  messages: AgentMessage[];
  entryIds: string[]; // parallel to messages — the session entry id for each message
  /** parallel to entryIds — the entry-level persistence timestamp (ms) for each message, when present */
  entryTimestamps?: (number | undefined)[];
  thinkingLevel: string;
  model: { provider: string; modelId: string } | null;
  /**
   * Compaction points on the visible message path — each one marks where the
   * kernel folded history into a summary. `beforeMessageEntryId` is the id of
   * the first visible message that comes AFTER this compaction; the UI inserts
   * a divider right before that message. Multiple entries appear when the
   * session was compacted several times and the kept messages still straddle
   * more than one boundary.
   */
  compactionPoints?: CompactionPoint[];
}

export interface CompactionPoint {
  /** The `compaction` entry id in the JSONL. */
  entryId: string;
  /** Context tokens before this compaction (from the entry's `tokensBefore`). */
  tokensBefore: number;
  /** The kernel's generated summary (markdown). */
  summary: string;
  /** First visible message after this compaction — divider goes right before it.
   *  Undefined when no visible message remains after this compaction (the
   *  session was compacted and no new messages were appended yet — the
   *  UI renders the divider as a trailing marker). */
  beforeMessageEntryId?: string;
  /** Compaction entry timestamp, when present. */
  timestamp?: string;
}

// RPC types
export interface SessionSearchResult {
  id: string;
  name?: string;
  cwd: string;
  modified: string;
  matchCount: number;
  snippet: string; // \u0000-delimited keyword markers for frontend highlighting
  /** entry.id of the first matching message — used to jump to that message on open */
  firstMatchEntryId?: string;
}

export interface SessionSearchResponse {
  results: SessionSearchResult[];
  hasMore: boolean;
}

/** A single message-level match within a session file */
export interface SessionMessageSearchResult {
  /** entry.id of the matching message */
  entryId: string;
  /** message role: user | assistant | toolResult */
  role: string;
  /** \u0000-delimited snippet for frontend <mark> highlighting */
  snippet: string;
  /** leaf entry id reachable from this message — used to switch branch when jumping */
  leafId: string;
  /** message timestamp if available */
  timestamp?: string;
}

export interface SessionMessageSearchResponse {
  /** First N results with snippets (for the result list) */
  results: SessionMessageSearchResult[];
  /** All matching entryIds (for <mark> highlighting in messages) */
  matchedEntryIds: string[];
  /** Total number of matching entryIds */
  totalMatches: number;
}

/**
 * Workspace row returned by GET /api/workspaces.
 *
 * Aggregates session-level metadata up to a cwd. Sorts by `lastUsed`
 * (max of that cwd's session modified timestamps) desc, with the active
 * cwd pinned to the front by the caller.
 *
 * `runningCount` comes from the in-memory AgentSessionWrapper registry —
 * cheap to recompute on every request. `totalSessions` requires a full
 * disk scan, so the route caches the full list with a 5s TTL (the same
 * window /api/sessions uses).
 */
export interface Workspace {
  cwd: string;
  /** max(session.modified) for sessions in this cwd — sort key */
  lastUsed: string;
  /** Number of session files in this cwd */
  totalSessions: number;
  /** Sessions currently between agent_start and agent_end in this cwd */
  runningCount: number;
  /** First message of the most recently modified session — sidebar hover tooltip */
  firstMessage: string;
  /** Name (if any) of the most recently modified session — sidebar hover tooltip */
  latestSessionName?: string;
}

export interface WorkspacesResponse {
  workspaces: Workspace[];
  /** base64url({lastUsed, cwd}) — opaque cursor; null means "no more" */
  nextCursor: string | null;
}

// ── Right-side button bar tab IDs ─────────────────────────────────────────
// Single source of truth for the global tab IDs the right button bar toggles.
// AppShell and SettingsModal both consume these.

export const TODO_TAB_ID = "todo:global";
export const FAVORITES_TAB_ID = "favorites:global";
export const TRANSLATE_TAB_ID = "translate:global";
export const TOOL_CALLS_TAB_ID = "toolCalls:global";
export const JSON_TAB_ID = "json:global";
export const CANVAS_TAB_ID = "canvas:global";
export const RSS_TAB_ID = "rss:global";
export const TOKENS_TAB_ID = "tokens:global";
export const GIT_DIFF_TAB_ID = "gitDiff:global";
export const CONVERSATION_TREE_TAB_ID = "conversationTree:global";
export const LLM_AUDIT_TAB_ID = "llmAudit:global";

// Map a Tab.kind back to the corresponding configurable right-bar button id.
// Used by AppShell's auto-close effect: when a panel whose button was just
// hidden is currently active, close the panel. "file" + "terminal"
// intentionally return undefined — those panels have no configurable
// button behind them and must stay open even if every toggle-button is
// hidden.
//
// Lives in lib/types.ts (not in components/rightBar/desc) to keep
// dependencies one-way: desc.tsx imports tab id constants from here,
// so this module can't re-export from desc without creating a cycle
// that crashes Turbopack at module evaluation time.
import type { RightBarButtonId } from "./config";
type TabKindForAutoClose =
  | "file"
  | "todo"
  | "canvas"
  | "translate"
  | "toolCalls"
  | "json"
  | "rss"
  | "favorites"
  | "tokens"
  | "gitDiff"
  | "conversationTree"
  | "llmAudit"
  | "terminal";
export const RIGHT_BAR_ID_FOR_TAB_KIND: Partial<
  Record<TabKindForAutoClose, RightBarButtonId>
> = {
  todo: "todos",
  canvas: "canvas",
  translate: "translate",
  json: "json",
  rss: "rss",
  favorites: "favorites",
  tokens: "tokens",
  toolCalls: "toolCalls",
  gitDiff: "gitDiff",
  conversationTree: "conversationTree",
  llmAudit: "llmAudit",
};
